version: '3.8'
services:
    haruhi:
        build: ./haruhi
        env_file: ./haruhi/.env
        ports:
            - "8111:80"
        volumes:
         - ./haruhi/app:/app
        tty: true
        env_file: ./haruhi/.env
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        env_file: ./yui/.env
        hostname: yui
        volumes:
         - db:/var/lib/mysql
volumes:
    db:
