version: '3.8'
services:
    misuzu:
        build: ./misuzu
        env_file: ./misuzu/.env
        ports:
            - "8111:80"
        volumes:
         - ./misuzu/app:/app
        tty: true
        command: uvicorn main:app --reload --host "0.0.0.0" --port "80"
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        env_file: ./yui/.env
        hostname: yui
        volumes:
         - db:/var/lib/mysql
    rikka:
        build: ./rikka
        restart: always
        env_file: ./rikka/.env
        volumes:
         - ./rikka:/home/root
        privileged: true
        tty: true
volumes:
    db:
