version: '3.8'
services:
    konata:
        build: ./konata
        ports:
         - "8484:80"
        volumes:
         - ./konata/conf.d/:/etc/nginx/conf.d
        depends_on:
         - misuzu
         - nagisa
    misuzu:
        build: ./misuzu
        env_file: ./misuzu/.env
        ports:
            - "8111:80"
        volumes:
         - ./misuzu/app:/app
        tty: true
        command: uvicorn main:app --reload --host "0.0.0.0" --port "80"
    nagisa:
        build: ./nagisa
        ports:
            - "3333:3000"
        volumes:
         - ./nagisa/app:/app
        tty: true
    yui:
        build:
            context: ./yui
            dockerfile: Dockerfile
        restart: always
        env_file: ./yui/.env
        hostname: yui
        volumes:
         - db:/var/lib/mysql
    eru:
        build:
            context: ./eru
            dockerfile: Dockerfile
        restart: always
        environment:
            - MB_DB_FILE=/metabase-data/metabase.db
        ports:
            - "3000:3000"
        volumes:
            - ./eru/metabase:/metabase-data
    rikka:
        build: ./rikka
        restart: always
        env_file: ./rikka/.env
        volumes:
         - ./rikka:/home/root
        privileged: true
        tty: true
volumes:
    db:
